### PR TITLE
moved header files and changed to be compatible with compileAttributes

### PR DESCRIPTION
**Pull request by duncan-clark**
Setup as Rproject to use Rstudio integrations. Building now fails which uses compileAttributes as part of the setup. Here is the error message. @ifellows  did you run into similar problems with moving LOLOG over to use compileAttributes - I have been through the commit history but cannot find the issue. It seems very similar to the LOLOG compileAttributes compatible setup.

image

### CODE REVIEW

**Comment by ifellows** [comment]
looking into it. First, the package didn't compile for me due to an error in asString (it used to work :| ). Change it to

```
/*!
 * Coerse a type into a string
 */
template<class T>
std::string asString(const T &item){
    std::ostringstream ss;
    ss << item;
    return ss.str();
}
```

**Comment by ifellows** [comment]
okay, so I very vaguely recalled the issue but couldn't remember what was wrong and how I fixed it. After banging at it for some time I realized my error. initStats and initToggles must be outside of the ernm namespace. For lolog I kicked initStats outside of the ernm namespace and then imported the namespace within the function (not FANTASTIC practice). See https://github.com/statnet/lolog/blob/202b0aa9532762a919b8dc4af79072e867bd28ff/src/StatController.cpp#L35 do it also in the .h files

**Comment by duncan-clark** [comment]
Made the changes for the ERNM namespace issues - how you figured out that this was the problem I have no idea.  Next up migrate testing to testthat.

**Comment by ifellows** [comment]
@duncan-clark . Well.... I suppose that the fact that the error was that the name couldn't be found should have led me to think that namespace might be an issue. That is probably what happened back when I solved the issue in lolog. That said, I had no recollection whatsoever yesterday of what the problem/solution was. I literally did a line by line comparison of the relevant .h/cpp files in ernm to lolog and noticed the scope difference.

btw, the best practice for this would be to not use `using namespace ernm;`. Importing namespaces is generally considered bad form in most cases. The better practice would be to have a function `ernmInitStats` in the namespace, and then a wrapper `initStats(){ernm::ernmInitStats();}` outside the namespace. No need to implement this, just FYI.

Is this ready to merge?

**Pull request merged**
